#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
# shellcheck source=/dev/null
. /run/monitor/X11/Xsession
